### ISSUE TITLE
`Feature Request`: Allow tutors to export the annotations as JSON (and re-import them later)

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/intelligrade#27]
Sometimes Artemis gets some hiccups when processing feedback and won't accept it.
To make sure tutors won't lose there feedback by accidentally (e.g. deleting the project from eclipse) there should be an option to export the created annotations as a file (preferably JSON, as there are Data-Object-Mappers implemented anyway).

**Comment by CDaut** [comment]
Should be pretty simple if Annotations in Artemis4J implement serialization.

**Comment by dfuchss** [comment]
@Feuermagier @Luro02 does artemis4j (new) has an API for that?

**Comment by Feuermagier** [comment]
Not yet, but we can use the Metajson API for that
