### ISSUE TITLE
Future Work: Figure out how to deal with tutor-made changes

### ISSUE THREAD

**Issue by RobinRSchulz** [kit-sdq/intelligrade#28]
We always want to make sure annotations are made to the actual student's submission.
Maybe throw a warning ==> Issue kit-sdq/programming-lecture-eclipse-artemis#52 (AlertHandler)

**Comment by Feuermagier** [comment]
All editors are now read-only, but we can't protect against moving files

**Comment by dfuchss** [comment]
I doubt that we will support protection against moving :D 

But RO means I'll close the issue 🥳
