### ISSUE TITLE
Improve UI for buttons tab

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/intelligrade#50]
![image](https://github.com/user-attachments/assets/856bf5d7-e9aa-4dbf-8dcc-ed47115405a4)

Improvements:
- [x] Make all buttons the same size (not based on their text)
- [ ] Add more (or less) rows depending on how much space is available in the window for the buttons
- [x] Distinct color for buttons that already exceeded the threshold
- [x] Distinct color for buttons that have been used (but not exceeded threshold)

**Comment by Feuermagier** [comment]
What colors do you think of? I'm feeling like adding too many colors makes the UI cluttered (also IntelliJ's design guidelines recommend using only very few colors). I've tried graying out buttons that only report and don't score, but they then look like they are disabled.

**Comment by Feuermagier** [comment]
I'm not sure how I could go about your second point without manually calculating the number of buttons that fit in a row. However, you adjust the number of buttons per row in the settings.

**Comment by dfuchss** [comment]
> I'm not sure how I could go about your second point without manually calculating the number of buttons that fit in a row. 

You can do the same as in the eclipse plugin. Just make the # columns configurable.

**Comment by Luro02** [comment]
> > I'm not sure how I could go about your second point without manually calculating the number of buttons that fit in a row.
> 
> You can do the same as in the eclipse plugin. Just make the # columns configurable.

I think the default were 3;
![image](https://github.com/user-attachments/assets/6ca6746a-3d13-40e0-84c4-e91dede319bb)

**Comment by Luro02** [comment]
> What colors do you think of? I'm feeling like adding too many colors makes the UI cluttered (also IntelliJ's design guidelines recommend using only very few colors). I've tried graying out buttons that only report and don't score, but they then look like they are disabled.

I was thinking of these pull requests https://github.com/kit-sdq/programming-lecture-eclipse-artemis/pull/338 and https://github.com/kit-sdq/programming-lecture-eclipse-artemis/pull/332, the default colors were:
- disabled button, no action: gray
- enabled button, no penalty: green
- enabled button, with penalty, no limit reached: yellow
- enabled button, with penalty, limit reached: magenta
