### ISSUE TITLE
Fix nix flake

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/intelligrade#59]
I got a report that the nix flake is not working anymore. I personally don't use nix, so I don't know how to fix this.

```
Execution failed for task ':verifyPluginProjectConfiguration'.
> Failed to query the value of task ':verifyPluginProjectConfiguration' property 'runtimeMetadata'.
   > Process 'command '~/.gradle/caches/8.10.2/transforms/ea8811f7aaec3ea2dbc3d3b7f371c02e/transformed/ideaIC-2024.2.1/jbr/bin/java'' finished with non-zero exit value 127
```

**Comment by lunagl** [comment]
Currently fixing this and I'm just wondering, why do we need `maven` and `jdt-language-server`?
<https://github.com/kit-sdq/intelligrade/blob/b2f0eb86225f9513c0b136273c1c58807b924a96/flake.nix#L27>
